{"name": "test_negative_create", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался 400, получен 404. Ответ: {\"timestamp\":\"2025-04-02T18:12:54.736+00:00\",\"status\":404,\"error\":\"Not Found\",\"path\":\"/api/v1/dashboard\"}\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "def test_negative_create():\n        response = requests.post(\n            f\"{BASE_URL}\",\n            headers={\"Authorization\": f\"Bearer {API_KEY}\"},\n            json={}\n        )\n        print(response.text)  # Для диагностики\n>       assert response.status_code == 400, f\"Ожидался 400, получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался 400, получен 404. Ответ: {\"timestamp\":\"2025-04-02T18:12:54.736+00:00\",\"status\":404,\"error\":\"Not Found\",\"path\":\"/api/v1/dashboard\"}\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest_api.py:29: AssertionError"}, "attachments": [{"name": "stdout", "source": "cb43236f-f63a-46c5-8b35-35d909d1745b-attachment.txt", "type": "text/plain"}], "start": 1743617529481, "stop": 1743617529777, "uuid": "937d8151-f390-4c1b-951d-b97a6a1cc8b6", "historyId": "81be286b62cba333e707460d0766ffc2", "testCaseId": "81be286b62cba333e707460d0766ffc2", "fullName": "test_api#test_negative_create", "labels": [{"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-A6SUBLI"}, {"name": "thread", "value": "9448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}