{"name": "test_negative_create", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался 400, получен 404. Ответ: {\"timestamp\":\"2025-04-02T18:11:18.072+00:00\",\"status\":404,\"error\":\"Not Found\",\"path\":\"/api/v1/dashboard\"}\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "def test_negative_create():\n        response = requests.post(\n            f\"{BASE_URL}\",\n            headers={\"Authorization\": f\"Bearer {API_KEY}\"},\n            json={}\n        )\n        print(response.text)  # Для диагностики\n>       assert response.status_code == 400, f\"Ожидался 400, получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался 400, получен 404. Ответ: {\"timestamp\":\"2025-04-02T18:11:18.072+00:00\",\"status\":404,\"error\":\"Not Found\",\"path\":\"/api/v1/dashboard\"}\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest_api.py:29: AssertionError"}, "attachments": [{"name": "stdout", "source": "fff23a5e-68cd-4b66-bfec-3229fbe33b0a-attachment.txt", "type": "text/plain"}], "start": 1743617432826, "stop": 1743617433117, "uuid": "7515c6be-0dbe-44b1-805d-d209c8311eaf", "historyId": "81be286b62cba333e707460d0766ffc2", "testCaseId": "81be286b62cba333e707460d0766ffc2", "fullName": "test_api#test_negative_create", "labels": [{"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-A6SUBLI"}, {"name": "thread", "value": "16736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}